// ######### PROJECTS REST API #####################################
// ###### LIST ALL PROJECTS
###
GET http://localhost:4001/api/projects_catalog

// ###### CREATE A NEW PROJECT
###
POST http://localhost:4001/api/projects_catalog
Content-Type: application/json

  {
    "id": null,
    "id_project_type": null,
    "project_name": "Proyecto Casa Habitacion 1 Piso",
    "project_duration": 30,
    "project_code": "ARQBID-001-CASAHAB1",
    "project_manager": " ",
    "project_details": "Proyecto de Casa Habitacion de 1 Piso 3 Recamaras 2 Baños",
    "projects_status": 1,
    "project_registration": "2020/11/27"
  }

// ###### SELECT ONE PROJECT BY ID
###
GET http://localhost:4001/api/projects_catalog/2

// ###### EDIT PROJECT BY ID
###
PUT http://localhost:4001/api/projects_catalog/105
Content-Type: application/json

  {
    "id": null,
    "id_project_type": null,
    "project_name": "Proyecto Casa Habitacion 1 Piso",
    "project_duration": 30,
    "project_code": "ARQBID-001-CASAHAB1",
    "project_manager": " ",
    "project_details": "Proyecto de Casa Habitacion de 1 Piso 3 Recamaras 2 Baños",
    "projects_status": 1,
    "project_registration": "2020/11/27"
  }

// ###### DELETE PROJECT BY ID
###
DELETE http://localhost:4001/api/projects_catalog/5